#!/bin/bash

ROOT=$(dirname $(readlink -f $0))/..
CALL_SITE=$(realpath $(pwd))

BUILD_OS="linux64"
if [[ "$OSTYPE" == "darwin"* ]]; then
	BUILD_OS="mac"
fi

VERSION="${BUILD_OS}_569e52e"

CALL_SITE=$CALL_SITE HAXE_STD_PATH=$ROOT/build/$VERSION/std $ROOT/build/$VERSION/haxe --cwd $ROOT run-hx.hxml $@
