#!/bin/bash

ROOT=$(dirname $(readlink -f $0))

if [ "$1" = "download" ]; then
	shift
	hx-download "$@"
elif [ ! -z "$1" ]; then
	if [ -e "$ROOT/../versions/$1" ]; then
		hx-select "$1"
	else
		echo "Haxe version not found: $1"
	fi
else
	current=$(haxe -version 2>&1)
	v=$(find "$ROOT/../versions/" -type l -exec basename {} \; | sort -r | fzf --prompt="Current: $current > ")

	if [ ! -z "$v" ]; then
		hx-select "$v"
	fi
fi
