name: CI
on: push

jobs:
  build-unix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      HAXE_STD_PATH: "${{ github.workspace }}/current/std"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Add to PATH
        run: |
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Install haxe-manager
        run: |
          ./install.sh
          # Rebuild hxb
          make build-tools

      - name: Check env
        run: |
          echo "PATH=${PATH}"
          echo "GITHUB_PATH=${GITHUB_PATH}"
          echo "HAXE_STD_PATH=${HAXE_STD_PATH}"

      - name: Check base usage
        run: |
          hx-download latest
          hx-download 4.3.4
          hx-download nightly 569e52e
          haxe --version
          hx-select dev
          haxe --version
          hx-select 4.3.4
          haxe --version

      - name: Install extra tools
        run: |
          sh ./extra/install-all.sh
          ls -Al bin/

      - name: Check list-haxe-versions
        run: list-haxe-versions

  build-windows:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      HAXE_STD_PATH: "${{ github.workspace }}/current/std"
    steps:
      - uses: actions/checkout@main

      - name: Add to PATH
        run: |
          echo "${env:GITHUB_WORKSPACE}/bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Install haxe-manager
        run: |
          ./install.bat
          haxe -version

      - name: Check env
        run: |
          echo "PATH=${env:PATH}"
          echo "GITHUB_PATH=${env:GITHUB_PATH}"
          echo "HAXE_STD_PATH=${env:HAXE_STD_PATH}"

      - name: Check base usage
        run: |
          hx-download latest
          hx-download 4.3.4
          hx-download nightly 569e52e
          haxe --version
          hx-select dev
          haxe --version
          hx-select 4.3.4
          haxe --version

