name: CI
on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest
    runs-on: ${{ matrix.os }}
    env:
      HAXE_STD_PATH: "${{ github.workspace }}/current/std"
    steps:
      - uses: actions/checkout@main

      - name: Add to PATH
        run: |
          # TODO: unix vs windows..
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH
          # echo "${env:GITHUB_WORKSPACE}/bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Install haxe-manager
        run: |
          sh ./install.sh --skip-defaults

      - name: Check env
        run: |
          # TODO: unix vs windows..
          echo "PATH=${env:PATH}"
          echo "GITHUB_PATH=${env:GITHUB_PATH}"
          echo "HAXE_STD_PATH=${env:HAXE_STD_PATH}"

      - name: Check base usage
        run: |
          # haxe --version
          # hx 4.2.5
          # hx dev
          hx-download latest
          ls -Al releases
          hx-download 4.3.4
          ls -Al releases
          hx-select dev
          haxe --version

      # TODO: unix only
      # - name: Install extra tools
      #   run: |
      #     sh ./extra/install-all.sh
      #     ls -Al bin/

      # TODO: unix only
      # - name: Check list-haxe-versions
      #   run: list-haxe-versions
